search_dirs_paths = [
    "media/axial-mri",
    "media/test1",
    "media/test2",
    "media/test3",
    "media/thermal-dogs-and-people"
  ]
  cache_path = ".cache"
  outlier_stddev_thresh = 6
  resize_dimensions = [ 256, 256 ]
  valid_file_extensions = [ "png", "jpg", "jpeg", "tif", "tiff" ]
  num_workers = 0
  