# paths
cache_path = ".cache"
search_dirs_paths = [
	"media/axial-mri",
	"media/test1",
	"media/test2",
	"media/test3",
	"media/thermal-dogs-and-people",
	"media/corrupted"
]

# performance
num_workers = 0
resize_dimensions = [ 256, 256 ]

# algorithm config
valid_file_extensions = [ "png", "jpg", "jpeg", "tif", "tiff" ]
outlier_zscore_thresh = 10
ratio_test_ratio = 0.5