# paths
cache_path = ".cache"
search_dirs_paths = [
	"media/axial-mri",
	"media/test1",
	"media/test2",
	"media/test3",
	"media/thermal-dogs-and-people",
	"media/corrupted",
	# "media/Golf Batch 4",
	# "media/Self Driving Car",
	# "media/Pascal VOC 2012",
	# "media/Buildings Instance Segmentation"
]

# display
print_live_analysis_results = true

# performance
num_workers = 0
resize_dimensions = [ 256, 256 ]

# algorithm config
valid_file_extensions = [ "png", "jpg", "jpeg", "tif", "tiff" ]
outlier_zscore_thresh = 10
ratio_test_ratio = 0.5